services:
  nacos:
    image: "nacos/nacos-server:v2.5.1"
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      - MODE=standalone
  prometheus:
    image: prom/prometheus:v3.2.0-rc.1
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  prometheuspush:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"
  grafana:
    image: grafana/grafana:11.5.1
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"